# Generated by Django 5.0.1 on 2024-01-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_board_image_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='total_stages',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='colour',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
