# Generated by Django 5.0.1 on 2024-01-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_board_total_stages_project_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='colour',
            field=models.CharField(blank=True, default='#000000', max_length=10, null=True),
        ),
    ]
