# Generated by Django 5.0.1 on 2024-01-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='text_colour',
            field=models.CharField(blank=True, default='#ffffff', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='colour',
            field=models.CharField(blank=True, default='#1e1e1e', max_length=10, null=True),
        ),
    ]
