# Generated by Django 5.0.1 on 2024-02-08 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_text_colour_alter_project_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='colour',
            field=models.CharField(blank=True, default='#1e1e1e', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='text_colour',
            field=models.CharField(blank=True, default='#ffffff', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boardgroup',
            name='colour',
            field=models.CharField(blank=True, default='#1e1e1e', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boardgroup',
            name='text_colour',
            field=models.CharField(blank=True, default='#ffffff', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_boards_set', to='project.boardgroup'),
        ),
        migrations.AlterField(
            model_name='board',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_boards_set', to='project.project'),
        ),
        migrations.AlterField(
            model_name='boardgroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_group_set', to='project.project'),
        ),
    ]
